/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include "e_gost_err.h"

#ifndef OPENSSL_NO_ERR

static ERR_STRING_DATA GOST_str_reasons[] = {
    {ERR_PACK(0, 0, GOST_R_BAD_KEY_PARAMETERS_FORMAT),
    "bad key parameters format"},
    {ERR_PACK(0, 0, GOST_R_BAD_MAC), "bad mac"},
    {ERR_PACK(0, 0, GOST_R_BAD_ORDER), "bad order"},
    {ERR_PACK(0, 0, GOST_R_BAD_PKEY_PARAMETERS_FORMAT),
    "bad pkey parameters format"},
    {ERR_PACK(0, 0, GOST_R_CANNOT_PACK_EPHEMERAL_KEY),
    "cannot pack ephemeral key"},
    {ERR_PACK(0, 0, GOST_R_CANNOT_UNPACK_EPHEMERAL_KEY),
    "cannot unpack ephemeral key"},
    {ERR_PACK(0, 0, GOST_R_CIPHER_NOT_FOUND), "cipher not found"},
    {ERR_PACK(0, 0, GOST_R_CTRL_CALL_FAILED), "ctrl call failed"},
    {ERR_PACK(0, 0, GOST_R_ERROR_COMPUTING_EXPORT_KEYS),
    "error computing export keys"},
    {ERR_PACK(0, 0, GOST_R_ERROR_COMPUTING_SHARED_KEY),
    "error computing shared key"},
    {ERR_PACK(0, 0, GOST_R_ERROR_PARSING_KEY_TRANSPORT_INFO),
    "error parsing key transport info"},
    {ERR_PACK(0, 0, GOST_R_ERROR_POINT_MUL), "error point mul"},
    {ERR_PACK(0, 0, GOST_R_INCOMPATIBLE_ALGORITHMS), "incompatible algorithms"},
    {ERR_PACK(0, 0, GOST_R_INCOMPATIBLE_PEER_KEY), "incompatible peer key"},
    {ERR_PACK(0, 0, GOST_R_INVALID_CIPHER), "invalid cipher"},
    {ERR_PACK(0, 0, GOST_R_INVALID_CIPHER_PARAMS), "invalid cipher params"},
    {ERR_PACK(0, 0, GOST_R_INVALID_CIPHER_PARAM_OID),
    "invalid cipher param oid"},
    {ERR_PACK(0, 0, GOST_R_INVALID_DIGEST_TYPE), "invalid digest type"},
    {ERR_PACK(0, 0, GOST_R_INVALID_IV_LENGTH), "invalid iv length"},
    {ERR_PACK(0, 0, GOST_R_INVALID_MAC_KEY_LENGTH), "invalid mac key length"},
    {ERR_PACK(0, 0, GOST_R_INVALID_MAC_KEY_SIZE), "invalid mac key size"},
    {ERR_PACK(0, 0, GOST_R_INVALID_MAC_PARAMS), "invalid mac params"},
    {ERR_PACK(0, 0, GOST_R_INVALID_MAC_SIZE), "invalid mac size"},
    {ERR_PACK(0, 0, GOST_R_INVALID_PARAMSET), "invalid paramset"},
    {ERR_PACK(0, 0, GOST_R_KEY_IS_NOT_INITIALIZED), "key is not initialized"},
    {ERR_PACK(0, 0, GOST_R_KEY_PARAMETERS_MISSING), "key parameters missing"},
    {ERR_PACK(0, 0, GOST_R_MAC_KEY_NOT_SET), "mac key not set"},
    {ERR_PACK(0, 0, GOST_R_NO_PARAMETERS_SET), "no parameters set"},
    {ERR_PACK(0, 0, GOST_R_NO_PEER_KEY), "no peer key"},
    {ERR_PACK(0, 0, GOST_R_NO_PRIVATE_PART_OF_NON_EPHEMERAL_KEYPAIR),
    "no private part of non ephemeral keypair"},
    {ERR_PACK(0, 0, GOST_R_PUBLIC_KEY_UNDEFINED), "public key undefined"},
    {ERR_PACK(0, 0, GOST_R_RNG_ERROR), "rng error"},
    {ERR_PACK(0, 0, GOST_R_SIGNATURE_MISMATCH), "signature mismatch"},
    {ERR_PACK(0, 0, GOST_R_SIGNATURE_PARTS_GREATER_THAN_Q),
    "signature parts greater than q"},
    {ERR_PACK(0, 0, GOST_R_UKM_NOT_SET), "ukm not set"},
    {ERR_PACK(0, 0, GOST_R_UNSUPPORTED_CIPHER_CTL_COMMAND),
    "unsupported cipher ctl command"},
    {ERR_PACK(0, 0, GOST_R_UNSUPPORTED_PARAMETER_SET),
    "unsupported parameter set"},
    {0, NULL}
};

#endif

static int lib_code = 0;
static int error_loaded = 0;

int ERR_load_GOST_strings(void)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();

    if (!error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(lib_code, GOST_str_reasons);
#endif
        error_loaded = 1;
    }
    return 1;
}

void ERR_unload_GOST_strings(void)
{
    if (error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(lib_code, GOST_str_reasons);
#endif
        error_loaded = 0;
    }
}

void ERR_GOST_error(int function, int reason, char *file, int line)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();
    ERR_raise(lib_code, reason);
    ERR_set_debug(file, line, NULL);
}
