/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_GOSTERR_H
# define HEADER_GOSTERR_H

# define GOSTerr(f, r) ERR_GOST_error((f), (r), OPENSSL_FILE, OPENSSL_LINE)


# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_GOST_strings(void);
void ERR_unload_GOST_strings(void);
void ERR_GOST_error(int function, int reason, char *file, int line);
# ifdef  __cplusplus
}
# endif

/*
 * GOST function codes.
 */
# define GOST_F_DECODE_GOST_ALGOR_PARAMS                  100
# define GOST_F_ENCODE_GOST_ALGOR_PARAMS                  101
# define GOST_F_FILL_GOST_EC_PARAMS                       102
# define GOST_F_GET_ENCRYPTION_PARAMS                     103
# define GOST_F_GOST89_GET_ASN1_PARAMETERS                104
# define GOST_F_GOST89_SET_ASN1_PARAMETERS                105
# define GOST_F_GOST_CIPHER_CTL                           106
# define GOST_F_GOST_EC_COMPUTE_PUBLIC                    107
# define GOST_F_GOST_EC_KEYGEN                            108
# define GOST_F_GOST_EC_SIGN                              109
# define GOST_F_GOST_EC_VERIFY                            110
# define GOST_F_GOST_GRASSHOPPER_CIPHER_CTL               111
# define GOST_F_GOST_GRASSHOPPER_SET_ASN1_PARAMETERS      112
# define GOST_F_GOST_IMIT_CTRL                            113
# define GOST_F_GOST_IMIT_FINAL                           114
# define GOST_F_GOST_IMIT_UPDATE                          115
# define GOST_F_MAGMA_IMIT_FINAL                          116
# define GOST_F_MAGMA_IMIT_UPDATE                         117
# define GOST_F_PARAM_COPY_GOST_EC                        118
# define GOST_F_PKEY_GOST2001_PARAMGEN                    119
# define GOST_F_PKEY_GOST2012_PARAMGEN                    120
# define GOST_F_PKEY_GOST_CTRL                            121
# define GOST_F_PKEY_GOST_ECCP_DECRYPT                    122
# define GOST_F_PKEY_GOST_ECCP_ENCRYPT                    123
# define GOST_F_PKEY_GOST_EC_CTRL_STR_256                 124
# define GOST_F_PKEY_GOST_EC_CTRL_STR_512                 125
# define GOST_F_PKEY_GOST_EC_DERIVE                       126
# define GOST_F_PKEY_GOST_MAC_CTRL                        127
# define GOST_F_PKEY_GOST_MAC_CTRL_STR                    128
# define GOST_F_PKEY_GOST_MAC_KEYGEN_BASE                 129
# define GOST_F_PKEY_GOST_MAC_SIGNCTX_INIT                130
# define GOST_F_PRINT_GOST_EC_PUB                         131
# define GOST_F_PRIV_DECODE_GOST                          132
# define GOST_F_PUB_DECODE_GOST_EC                        133
# define GOST_F_PUB_ENCODE_GOST_EC                        134
# define GOST_F_UNPACK_CP_SIGNATURE                       135
# define GOST_F_VKO_COMPUTE_KEY                           136

/*
 * GOST reason codes.
 */
# define GOST_R_BAD_KEY_PARAMETERS_FORMAT                 100
# define GOST_R_BAD_PKEY_PARAMETERS_FORMAT                101
# define GOST_R_CANNOT_PACK_EPHEMERAL_KEY                 102
# define GOST_R_CTRL_CALL_FAILED                          103
# define GOST_R_ERROR_COMPUTING_SHARED_KEY                104
# define GOST_R_ERROR_PARSING_KEY_TRANSPORT_INFO          105
# define GOST_R_ERROR_POINT_MUL                           106
# define GOST_R_INCOMPATIBLE_ALGORITHMS                   107
# define GOST_R_INCOMPATIBLE_PEER_KEY                     108
# define GOST_R_INVALID_CIPHER_PARAMS                     109
# define GOST_R_INVALID_CIPHER_PARAM_OID                  110
# define GOST_R_INVALID_DIGEST_TYPE                       111
# define GOST_R_INVALID_IV_LENGTH                         112
# define GOST_R_INVALID_MAC_KEY_LENGTH                    113
# define GOST_R_INVALID_MAC_KEY_SIZE                      114
# define GOST_R_INVALID_MAC_PARAMS                        115
# define GOST_R_INVALID_MAC_SIZE                          116
# define GOST_R_INVALID_PARAMSET                          117
# define GOST_R_KEY_IS_NOT_INITIALIZED                    118
# define GOST_R_KEY_PARAMETERS_MISSING                    119
# define GOST_R_MAC_KEY_NOT_SET                           120
# define GOST_R_NO_PARAMETERS_SET                         121
# define GOST_R_NO_PEER_KEY                               122
# define GOST_R_NO_PRIVATE_PART_OF_NON_EPHEMERAL_KEYPAIR  123
# define GOST_R_PUBLIC_KEY_UNDEFINED                      124
# define GOST_R_RNG_ERROR                                 125
# define GOST_R_SIGNATURE_MISMATCH                        126
# define GOST_R_SIGNATURE_PARTS_GREATER_THAN_Q            127
# define GOST_R_UKM_NOT_SET                               128
# define GOST_R_UNSUPPORTED_CIPHER_CTL_COMMAND            129
# define GOST_R_UNSUPPORTED_PARAMETER_SET                 130

#endif
